# Generated by Django 5.0.4 on 2024-05-19 17:31

import newsletter.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="post",
            new_name="message",
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="article",
            name="sortorder",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sort order determines the order in which articles are concatenated in a message.",
                verbose_name="sort order",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="site",
            field=models.ManyToManyField(
                default=newsletter.utils.get_default_sites, to="sites.site"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together={("message", "sortorder")},
        ),
    ]
