# Generated by Django 5.0.3 on 2024-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelformtest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingEmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
    ]
