# Generated by Django 5.0.3 on 2024-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelformtest", "0003_testmodel_is_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="unsubscribe_token",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
