# Generated by Django 5.0.3 on 2024-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelformtest", "0004_testmodel_unsubscribe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
